name: relembrando-ci-cd
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  primeiro_job:
    name: 'meu job'
    runs-on: ubuntu-20.04
    steps:
      - name: 'msg 1'
        run: echo 'hello world'
      - name: 'msg 2'
        run: echo 'hello world'
      - name: 'msg 3'
        shell: python
        run: print('msg 4')
